import Providers from "./providers";
import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html suppressHydrationWarning className={sans.className}>
            <body className="flex flex-col bg-background-default dark:bg-background-dark">
                <Providers>
                    <Navbar />

                    {children}
                </Providers>
            </body>
        </html>
    );
}
